### ISSUE TITLE
Can't Create Oauth Authorization

### ISSUE THREAD

**Issue by dcwalker-500** [pluginsGLPI/doc#62]
I have followed the Oauth IMAP Domination for configuration.  I will hit the Create an Authorization button and sign in with no issues will get prompted to accept the permissions hit the accepted and then will get redirected to the GLPI Dashboard page and will go to the Oauth IMAP application and see that we have no authorized users.  I am not sure what the issue is.

**Comment by trasher** [comment]
Seems not related to glpi core documentation
